# usage:
#   conda env create -f environment.yml
#   conda activate merp2tbl
---
name: merp2table
channels:
    - conda-forge
dependencies:
    - pytest
    - pytest-cov
    - python>=3.6
    - pyyaml
    - yamllint
